### ISSUE TITLE
Compiling source from git to the new ESP is not working

### ISSUE THREAD

**Issue by karincalab** [mirobot/mirobot-wifi#2]
Hi,

Thanks for your great job with mirobot. I got the source code and after lots of effor I managed to compile it(still couldn't success with esptool2). After programming the arduino and connecting to wifi it is not working. I can't see the mirobot in wifi searc. Could you please help me on this, I want to use this code one of my scool project but first I need to get it work.

**Comment by bjpirt** [comment]
What do you mean by "still couldn't success with esptool2" ?

**Comment by karincalab** [comment]
As you said, I uncommented the stdoutInit(); and now I am getting this error:

{"status":"error", "msg":"Message too long"}
{"status":"error", "msg":"Message too long"}

**Comment by bjpirt** [comment]
Sorry, didn't see your reply until now - I'm guessing you got this sorted since I didn't hear back from you.
