### ISSUE TITLE
problems compiling

### ISSUE THREAD

**Issue by HenkATwaag** [mirobot/mirobot-wifi#3]
after a fresh install of esp-open-sdk and mirobot-wifi i get the following errors during compiling.

Squash html/index.html
MAKE libesphttpd/libesphttpd.a
make[1]: Entering directory '/home/henk/mirobot-wifi/libesphttpd'
CC espfs/espfs.c
In file included from ./include/esp8266.h:11:0,
                 from espfs/espfs.c:23:
/opt/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/include/ets_sys.h:14:1: error: unknown type name 'uint32_t'
 typedef uint32_t ETSSignal;
 ^
/opt/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/include/ets_sys.h:15:1: error: unknown type name 'uint32_t'
 typedef uint32_t ETSParam;
 ^
/opt/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/include/ets_sys.h:27:1: error: unknown type name 'uint32_t'
 typedef uint32_t ETSHandle;
 ^
/opt/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/include/ets_sys.h:32:5: error: unknown type name 'uint32_t'
     uint32_t              timer_expire;
     ^
/opt/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/include/ets_sys.h:33:5: error: unknown type name 'uint32_t'
     uint32_t              timer_period;
     ^
In file included from ./include/esp8266.h:16:0,
                 from espfs/espfs.c:23:
/opt/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/include/user_interface.h:329:1: error: unknown type name 'uint8_t'
 void wifi_promiscuous_set_mac(const uint8_t _address);
 ^
In file included from espfs/espfs.c:40:0:
espfs/espfsformat.h:25:2: error: unknown type name 'int32_t'
  int32_t magic;
  ^
espfs/espfsformat.h:26:2: error: unknown type name 'int8_t'
  int8_t flags;
  ^
espfs/espfsformat.h:27:2: error: unknown type name 'int8_t'
  int8_t compression;
  ^
espfs/espfsformat.h:28:2: error: unknown type name 'int16_t'
  int16_t nameLen;
  ^
espfs/espfsformat.h:29:2: error: unknown type name 'int32_t'
  int32_t fileLenComp;
  ^
espfs/espfsformat.h:30:2: error: unknown type name 'int32_t'
  int32_t fileLenDecomp;
  ^
In file included from espfs/espfs.c:45:0:
lib/heatshrink/heatshrink_decoder.h:45:5: error: unknown type name 'uint16_t'
     uint16_t input_size;        /_ bytes in input buffer _/
     ^
lib/heatshrink/heatshrink_decoder.h:46:5: error: unknown type name 'uint16_t'
     uint16_t input_index;       /_ offset to next unprocessed input byte _/
     ^
lib/heatshrink/heatshrink_decoder.h:47:5: error: unknown type name 'uint16_t'
     uint16_t output_count;      /_ how many bytes to output _/
     ^
lib/heatshrink/heatshrink_decoder.h:48:5: error: unknown type name 'uint16_t'
     uint16_t output_index;      /_ index for bytes to output _/
     ^
lib/heatshrink/heatshrink_decoder.h:49:5: error: unknown type name 'uint16_t'
     uint16_t head_index;        /_ head of window buffer _/
     ^
lib/heatshrink/heatshrink_decoder.h:50:5: error: unknown type name 'uint16_t'
     uint16_t bit_accumulator;
     ^
lib/heatshrink/heatshrink_decoder.h:51:5: error: unknown type name 'uint8_t'
     uint8_t state;              /_ current state machine node _/
     ^
lib/heatshrink/heatshrink_decoder.h:52:5: error: unknown type name 'uint8_t'
     uint8_t current_byte;       /_ current byte of input _/
     ^
lib/heatshrink/heatshrink_decoder.h:53:5: error: unknown type name 'uint8_t'
     uint8_t bit_index;          /_ current bit index _/
     ^
lib/heatshrink/heatshrink_decoder.h:57:5: error: unknown type name 'uint8_t'
     uint8_t window_sz2;         /_ window buffer bits _/
     ^
lib/heatshrink/heatshrink_decoder.h:58:5: error: unknown type name 'uint8_t'
     uint8_t lookahead_sz2;      /_ lookahead bits _/
     ^
lib/heatshrink/heatshrink_decoder.h:59:5: error: unknown type name 'uint16_t'
     uint16_t input_buffer_size; /_ input buffer size _/
     ^
lib/heatshrink/heatshrink_decoder.h:62:5: error: unknown type name 'uint8_t'
     uint8_t buffers[];
     ^
lib/heatshrink/heatshrink_decoder.h:76:46: error: unknown type name 'uint16_t'
 heatshrink_decoder *heatshrink_decoder_alloc(uint16_t input_buffer_size,
                                              ^
lib/heatshrink/heatshrink_decoder.h:77:5: error: unknown type name 'uint8_t'
     uint8_t expansion_buffer_sz2, uint8_t lookahead_sz2);
     ^
lib/heatshrink/heatshrink_decoder.h:77:35: error: unknown type name 'uint8_t'
     uint8_t expansion_buffer_sz2, uint8_t lookahead_sz2);
                                   ^
lib/heatshrink/heatshrink_decoder.h:89:5: error: unknown type name 'uint8_t'
     uint8_t *in_buf, size_t size, size_t *input_size);
     ^
lib/heatshrink/heatshrink_decoder.h:94:5: error: unknown type name 'uint8_t'
     uint8_t *out_buf, size_t out_buf_size, size_t *output_size);
     ^
espfs/espfs.c:54:2: error: unknown type name 'int32_t'
  int32_t posDecomp;
  ^
espfs/espfs.c: In function 'espFsFlags':
espfs/espfs.c:122:2: error: unknown type name 'int8_t'
  int8_t flags;
  ^
espfs/espfs.c: In function 'espFsOpen':
espfs/espfs.c:161:4: error: too many arguments to function 'pvPortMalloc'
    r=(EspFsFile *)os_malloc(sizeof(EspFsFile)); //Alloc file desc mem
    ^
In file included from ./include/esp8266.h:18:0,
                 from espfs/espfs.c:23:
./include/espmissingincludes.h:37:7: note: declared here
 void *pvPortMalloc(size_t xWantedSize);
       ^
espfs/espfs.c:180:5: error: implicit declaration of function 'heatshrink_decoder_alloc' [-Werror=implicit-function-declaration]
     dec=heatshrink_decoder_alloc(16, (parm>>4)&0xf, parm&0xf);
     ^
espfs/espfs.c:180:8: error: assignment makes pointer from integer without a cast [-Werror]
     dec=heatshrink_decoder_alloc(16, (parm>>4)&0xf, parm&0xf);
        ^
espfs/espfs.c: In function 'espFsRead':
espfs/espfs.c:234:5: error: implicit declaration of function 'heatshrink_decoder_sink' [-Werror=implicit-function-declaration]
     heatshrink_decoder_sink(dec, (uint8_t *)ebuff, (elen>16)?16:elen, &rlen);
     ^
espfs/espfs.c:234:35: error: 'uint8_t' undeclared (first use in this function)
     heatshrink_decoder_sink(dec, (uint8_t *)ebuff, (elen>16)?16:elen, &rlen);
                                   ^
espfs/espfs.c:234:35: note: each undeclared identifier is reported only once for each function it appears in
espfs/espfs.c:234:44: error: expected expression before ')' token
     heatshrink_decoder_sink(dec, (uint8_t *)ebuff, (elen>16)?16:elen, &rlen);
                                            ^
espfs/espfs.c:238:4: error: implicit declaration of function 'heatshrink_decoder_poll' [-Werror=implicit-function-declaration]
    heatshrink_decoder_poll(dec, (uint8_t *)buff, len-decoded, &rlen);
    ^
espfs/espfs.c:238:43: error: expected expression before ')' token
    heatshrink_decoder_poll(dec, (uint8_t *)buff, len-decoded, &rlen);
                                           ^
espfs/espfs.c: In function 'espFsClose':
espfs/espfs.c:270:2: error: too many arguments to function 'vPortFree'
  os_free(fh);
  ^
In file included from ./include/esp8266.h:18:0,
                 from espfs/espfs.c:23:
./include/espmissingincludes.h:40:6: note: declared here
 void vPortFree(void *ptr);
      ^
cc1: all warnings being treated as errors
Makefile:151: recipe for target 'build/espfs/espfs.o' failed
make[1]: *_\* [build/espfs/espfs.o] Error 1
make[1]: Leaving directory '/home/henk/mirobot-wifi/libesphttpd'
Makefile:133: recipe for target 'libesphttpd/libesphttpd.a' failed
make: **\* [libesphttpd/libesphttpd.a] Error 2

**Comment by bjpirt** [comment]
Hi, for some reason there are issues around the c types in the sdk - I found that if I use the definitions in sdk/include/c_types.h.old instead of the ones in c_types.h it works. Just switch the filenames and it should work. I'm not sure why this is.

**Comment by mataqvazadeh** [comment]
Hi,
I have same problem but I couldn't solve my problem with your solution.
There is two c_type files in include directory as you said and their names are "c_type.h" and "c_type.orig". I swapped names but I got same error again.
