### ISSUE TITLE
Makefile error?

### ISSUE THREAD

**Issue by Mike-Jupp** [mirobot/mirobot-wifi#5]
Hi,

I have built the toolchain using the recommended process (esp-open-sdk) and compiled the blinky example OK, so I guess I have it set up correctly.

I put your WiFi directory in the same directory as examples and tried to compile it with 'make'. I get errors about 'ruby' .  I know very little about make files but at looking at this one I see the line:
SDK_BASE ?= /opt/Espressif/ESP8266_SDK

Of course having used esp-open-sdk to build the toolchain the SDK is not there. I wonder if this has anything to do with it.

I would appreciate some guidance!

thanks

Mike

**Comment by Mike-Jupp** [comment]
Hi Mike again,

Learning a lot about Make files and Linux in general.  I have managed to alter the PATH so it picks up the right compiler. Now , having got over a few problems I now get stuck at a line in mdns.c:
struct mdns_info *info = (struct mdns_info *)os_zalloc(sizeof(struct mdns_info));
I can't see anything wrong with it apart from the fact it seems a bit iterative.  The compiler however says 'incomplete type 'struct mdns_info'

**Comment by bjpirt** [comment]
Not sure what's going on there. It's most likely to do with the SDK changing. I think it's possible to install a specific version of the SDK so if you can try with v1.3.0 that's the version that the main firmware was built with.
